title: "Kexin Zhang"
description: "Academic Homepage"
url: "https://zkx9218-arch.github.io"
baseurl: ""

markdown: kramdown
# theme: minima

# 个人信息（左侧栏用）
profile:
  name: "Kexin Zhang"
  name_cn: "张柯鑫"
  role: "Undergraduate Student"
  org: "Chang'an University"
  location: "Xian,China"
  email: "2025906198.chd.edu.cn"
  avatar: "/assets/img/avatar.jpg"
  links:
    - label: "GitHub"
      url: "https://github.com/zkx9218-arch"
    - label: "Google Scholar"
      url: "https://scholar.google.com/"
    - label: "ResearchGate"
      url: "https://www.researchgate.net/"

# News（主页展示）
news:
  - date: "2026-01"
    text: "We are developing FlowSim2D"

selected_publications:

  - title: "Challenge Cup China College Student Entrepreneurship Competition (Gold Award)"
    authors: "Team Leader: Kexin Zhang · Chang'an University · National Competition, 2025"
    venue: ""
    bullets:
      - "Project Leader."
      - "Responsible for overall project design and implementation."
      - "Completed model development, experimental analysis, and final presentation."
    links:
      - label: "Project"
        url: "#"
    image: "/assets/img/pubs/paper1.jpg"

  - title: "Chang'an University 'Entrepreneurship Pioneer' Challenge (Gold Award)"
    authors: "Team Member: Kexin Zhang · Chang'an University"
    venue: ""
    bullets:
      - "Project Team Member."
      - "Participated in overall project design and implementation."
      - "Contributed to model development, experimental analysis, and presentation."
    links:
      - label: "Report"
        url: "#"
    image: "/assets/img/pubs/paper2.jpg"








